// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  AUSTIN_CODES: SmartBucket;
  CEREBRAS_API_KEY: string;
  ELEVENLABS_AGENT_ID: string;
  ELEVENLABS_API_KEY: string;
  FEES_DB: SmartSql;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
  USER_CONTEXT: SmartMemory;
  VULTR_BRIDGE_URL: string;
}
